/**
 * Translates D1/SQLite SQL (used by @vmp/api) into PostgreSQL for Deno Deploy managed SQL.
 * Deno Deploy cannot load native addons (better-sqlite3); the Worker code stays unchanged.
 */

/** Replace `?` placeholders outside string literals with `$1`, `$2`, … */
export function bindQuestionMarks(sql: string, paramCount: number): string {
  if (paramCount === 0) return sql
  let index = 0
  let out = ''
  let inSingle = false
  let inDouble = false
  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i]
    const prev = sql[i - 1]
    if (ch === "'" && !inDouble && prev !== '\\') {
      inSingle = !inSingle
      out += ch
      continue
    }
    if (ch === '"' && !inSingle && prev !== '\\') {
      inDouble = !inDouble
      out += ch
      continue
    }
    if (ch === '?' && !inSingle && !inDouble) {
      index += 1
      if (index > paramCount) {
        throw new Error(`SQL has more ? placeholders than bound parameters (${paramCount})`)
      }
      out += `$${index}`
      continue
    }
    out += ch
  }
  if (index !== paramCount) {
    throw new Error(`SQL has ${index} ? placeholders but ${paramCount} parameters were bound`)
  }
  return out
}

/** Runtime + migration SQL dialect tweaks (SQLite → PostgreSQL). */
export function translateSqliteToPostgres(sql: string): string {
  let s = sql.trim()

  // Strip SQLite PRAGMA (Postgres uses different session settings).
  s = s.replace(/^\s*PRAGMA\s+[^;]+;\s*/gim, '')

  // sqlite_master introspection (admin health / seed helpers in @vmp/api).
  s = s.replace(
    /FROM\s+sqlite_master\b/gi,
    "FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'",
  )
  s = s.replace(/\btype\s*=\s*'table'/gi, "table_type = 'BASE TABLE'")

  // PRAGMA table_info(tbl) → information_schema (used by brevo + kv bootstrap).
  s = s.replace(/PRAGMA\s+table_info\s*\(\s*([`'"]?)(\w+)\1\s*\)/gi, (_m, _q, table) => {
    return `SELECT column_name AS name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '${table}'`
  })

  const hadInsertOrIgnore = /\bINSERT\s+OR\s+IGNORE\s+INTO\b/i.test(s)

  // DML compatibility
  s = s.replace(/\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi, 'INSERT INTO')
  s = s.replace(/\bINSERT\s+OR\s+REPLACE\s+INTO\b/gi, 'INSERT INTO')
  s = s.replace(/\bREPLACE\s+INTO\b/gi, 'INSERT INTO')

  // Postgres requires ON CONFLICT for ignore semantics (SQLite INSERT OR IGNORE).
  if (hadInsertOrIgnore && /\bINSERT\s+INTO\b/i.test(s) && !/\bON\s+CONFLICT\b/i.test(s)) {
    s = `${s.replace(/;\s*$/, '')} ON CONFLICT DO NOTHING`
  }

  // datetime('now', modifier) — SQLite modifier strings
  s = s.replace(
    /datetime\s*\(\s*'now'\s*,\s*'\+(\d+)\s+seconds'\s*\)/gi,
    (_m, sec) => `(CURRENT_TIMESTAMP + interval '${sec} seconds')`,
  )
  s = s.replace(
    /datetime\s*\(\s*'now'\s*,\s*'-(\d+)\s+hours'\s*\)/gi,
    (_m, hrs) => `(CURRENT_TIMESTAMP - interval '${hrs} hours')`,
  )
  s = s.replace(
    /datetime\s*\(\s*'now'\s*,\s*'\+(\d+)\s+minutes'\s*\)/gi,
    (_m, min) => `(CURRENT_TIMESTAMP + interval '${min} minutes')`,
  )
  s = s.replace(/datetime\s*\(\s*'now'\s*\)/gi, 'CURRENT_TIMESTAMP')

  // datetime(column, modifier) — brevo claim timeouts
  s = s.replace(
    /datetime\s*\(\s*'now'\s*,\s*\?\s*\)/gi,
    "(CURRENT_TIMESTAMP + (?::text || ' seconds')::interval)",
  )
  s = s.replace(
    /datetime\s*\(\s*created_at\s*,\s*\?\s*\)/gi,
    "(created_at::timestamptz + (?::text || ' seconds')::interval)",
  )

  // datetime(expr) comparisons — treat text timestamps as timestamptz
  s = s.replace(/datetime\s*\(\s*([a-zA-Z0-9_.]+)\s*\)/g, '($1::timestamptz)')

  s = s.replace(/\bunixepoch\s*\(\s*\)/gi, 'EXTRACT(EPOCH FROM NOW())::bigint')
  s = s.replace(
    /\bunixepoch\s*\(\s*\)\s*<\s*unixepoch\s*\(\s*\)/gi,
    'EXTRACT(EPOCH FROM NOW()) < EXTRACT(EPOCH FROM NOW())',
  )
  s = s.replace(
    /expires_at\s*<\s*unixepoch\s*\(\s*\)/gi,
    'expires_at < EXTRACT(EPOCH FROM NOW())::bigint',
  )
  s = s.replace(
    /expires_at\s*>=\s*unixepoch\s*\(\s*\)/gi,
    'expires_at >= EXTRACT(EPOCH FROM NOW())::bigint',
  )
  s = s.replace(/\bunixepoch\s*\(\s*\)/gi, 'EXTRACT(EPOCH FROM NOW())::bigint')

  // strftime (analytics)
  s = s.replace(
    /strftime\s*\(\s*'%Y-W%W'\s*,\s*datetime\s*\(\s*([^)]+)\s*\)\s*\)/gi,
    "to_char(($1)::timestamptz, 'IYYY-\"W\"IW')",
  )
  s = s.replace(
    /strftime\s*\(\s*'%Y-%m'\s*,\s*datetime\s*\(\s*([^)]+)\s*\)\s*\)/gi,
    "to_char(($1)::timestamptz, 'YYYY-MM')",
  )
  s = s.replace(/date\s*\(\s*datetime\s*\(\s*([^)]+)\s*\)\s*\)/gi, '(($1)::timestamptz)::date')

  return s
}

/** DDL tweaks when applying packages/api/migrations/*.sql to Postgres. */
export function translateSqliteDdl(sql: string): string {
  let s = translateSqliteToPostgres(sql)
  s = s.replace(/\bDATETIME\b/gi, 'TIMESTAMPTZ')
  s = s.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'BIGSERIAL PRIMARY KEY')
  s = s.replace(/\bAUTOINCREMENT\b/gi, 'GENERATED BY DEFAULT AS IDENTITY')
  s = s.replace(/datetime\s*\(\s*'now'\s*\)/gi, 'CURRENT_TIMESTAMP')
  s = s.replace(/DEFAULT\s*\(\s*datetime\s*\(\s*'now'\s*\)\s*\)/gi, 'DEFAULT CURRENT_TIMESTAMP')
  return s
}
